### Numpy Installation

In [3]:
#numpy
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [6]:
#importing numpy
import numpy as np

#creating numpy

a = np.array([1,2,3])
b = np.array([(1.5,2,3),(4,5,6,)])
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]])
print(a)
print(b)
print(c)             

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [39]:
import numpy as np
a = np.array(['kittu','saikrishna'])
b = np.array([('sai','krishna','pranay'),('pranay','vamsi','vasu')])
c = np.array([[('reddy','krishna','sai'),('python','coding','challange')],[('cat','ball','tie'),(4,5,6)]])
print(a)
print(b)
print(c)

['kittu' 'saikrishna']
[['sai' 'krishna' 'pranay']
 ['pranay' 'vamsi' 'vasu']]
[[['reddy' 'krishna' 'sai']
  ['python' 'coding' 'challange']]

 [['cat' 'ball' 'tie']
  ['4' '5' '6']]]


In [76]:
#intial placeholders
#create an array og zeros
f = np.zeros((2,10))
print(f)

s = np.zeros((10,5))
print(s)

#creating an array of ones
d = np.ones((2,3,4))
print(d)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [102]:
#creating an array of evenly space
d = np.arange(10,25,3) #steps n-1(3-1=2)
print(d)

f = np.arange(25,100,50)
print(f)

[10 13 16 19 22]
[25 75]


In [109]:
##creating an array evenly spced values
np.linspace(10,80,10)

array([10.        , 17.77777778, 25.55555556, 33.33333333, 41.11111111,
       48.88888889, 56.66666667, 64.44444444, 72.22222222, 80.        ])

In [129]:
#creating a constant array
e = np.full((6),9)
print(e)
print(e.ndim)

d = np.full((11),0)
print(d)
print(d.ndim)

f = np.full((6,4),9)
print(f)
print(f.ndim)

a = np.full((2,6,4),5)#shape,row,column
print(a)
print(a.ndim)

[9 9 9 9 9 9]
1
[0 0 0 0 0 0 0 0 0 0 0]
1
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
2
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]
3


In [135]:
#create a 2*2 identity matrix
f = np.eye(2)
print(f)

d = np.eye(4)
print(d)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [142]:
#creating an array with random values
np.random.random((2,3))

array([[0.52414386, 0.28701346, 0.15883661],
       [0.9044315 , 0.90008277, 0.03230925]])

In [152]:
#finding the size of array
arr = np.array ([[2,3],
                 [4,5]])
print(arr.size)

d = np.array ([[2,3],
               [2,7],
               [5,2],
               [34,5],
               [4,5]])
print(d.size)

4
10


In [162]:
#finding the len of array
arr = np.array([[2,4],
                [6,2],
                [9,2],
                [4,7]])
print(len(arr))

d =  np.array([[2,4],
               [6,2],
               [9,2],
               [23,45],
               [32,45],
               [23,46],
               [4,7]])
print(len(d))

4
7


In [8]:
#acccess array elements:
arr = np.array([1,2,3,4])
print(arr[2])

3


In [30]:
#adding two index position
arr = np.array([1,2,3,4])

print(arr[2] + arr[3] + arr[0])
print(arr[0] - arr[3])
print(arr[1] * arr[3])
print(arr[2] % arr[2])
print(arr[1] / arr[3])
print(arr[2] ** arr[3])
print(arr[3] // arr[1])

8
-3
8
0
0.5
81
2


In [60]:
#accessing 2dim array elements
arr = np.array([[1,2,3,4,5],
              [6,7,8,9,2],
              [5,4,3,2,1],
              [2,3,4,5,6]])
print('2nd element on 1st row:',arr[1,2])


arr = np.array([[1,2,3,4,5],
              [6,7,8,9,2],
              [5,4,3,2,1],
              [2,3,4,5,6]])
print('3rd element of 2nd row:',arr[2,3])

2nd element on 1st row: 8
3rd element of 2nd row: 2


In [72]:
#accessing 3dim array elements
arr = np.array([[[1,2,3],[3,2,1]],  
                [[4,5,6],[6,19,4]],
                [[7,8,11],[9,8,7]],
                [[1,4,17],[3,6,91]]])
print(arr[1,0,1])

arr = np.array([[[1,2,3],[3,2,1]],  
                [[4,5,6],[6,19,15]],
                [[7,8,11],[9,8,7]],
                [[1,4,17],[3,6,91]]])
print(arr[1,1,2])

5
15


In [104]:
#data types 
#string
arr = np.array([1,2,3,4],dtype = 'S')
print(arr)
print(arr.dtype)

arr = np.array([3,0,7,8],dtype = 'i')
print(arr)
print(arr.dtype)               

          

[b'1' b'2' b'3' b'4']
|S1
[3 0 7 8]
int32


In [100]:
#integer
arr = np.array([1,2,3,4],dtype = 'f')
print(arr)
print(arr.dtype)

arr = np.array([765,3,45],dtype = 'S')
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32
[b'765' b'3' b'45']
|S3


In [112]:
#bool 
arr = np.array([1,0,3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

arr = np.array([0,1,-2])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool
[False  True  True]
bool


In [116]:
#change 
arr = np.array([1.2,3.2,2.5])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 3 2]
int32


In [122]:
#copy method
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[4]=234
print(arr)
print(x)

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0]=4523
print(arr)
print(x)

[  1   2   3   4 234]
[1 2 3 4 5]
[4523    2    3    4    5]
[1 2 3 4 5]


In [132]:
#view method
arr = np.array([1,7,3,4,5])
x = arr.view()
arr[1] = 2
print(x)

#
arr = np.array([123,34,43,45])
x = arr.view()
arr[0] = 76
print(x)

[1 2 3 4 5]
[76 34 43 45]


In [146]:
#shape
arr = np.array([[9,8,7,6],[2,3,4,5],[2,45,5,2]])
              
print(arr.shape)

(3, 4)
